### PR TITLE
[WIP] Header menu, content view, and setup wizard from mockup

### PR DESCRIPTION
**Pull request by willy-b**
Working on the top menu from the 1st mockup. "View all", "Settings", and "+" buttons work to toggle those views. Mousing over the top menu fades in the search bar, but the search bar is nonfunctional.

### CODE REVIEW

**Comment by willy-b** [comment]
I see some new mockups came out on Friday. Am going to finish wiring this up and then will adapt to those in a separate PR. This PR is for the original mockups (for now)

**Comment by willy-b** [comment]
- Just pushed a basic content view allowing you to view Content body content. 
- Added fragment URL based routing so you can back/forward and bookmark a piece of content.

**Comment by willy-b** [comment]
Single piece of content view (in progress):
Datt viewing single piece of content - WIP

Front-page view (in progress):
Datt front page - WIP

**Comment by kwolk** [comment]
Wow, the first post!

How much longer for this decentralised Reddit before we can all post?

**Comment by willy-b** [comment]
Added 'REPLY' and HEART buttons per Chris' mockup
Datt content view (WIP) with 'REPLY' and HEART buttons per Chris' mockup

**Comment by willy-b** [comment]
Datt initial setup modal WIP (from Chris' excellent mockup as always):
Datt initial setup modal WIP

'#/setup' route maps to it

**Comment by willy-b** [comment]
@kwolk Soon I hope; best place to keep up with plans, etc is in the Datt slack: dattnetwork.slack.com

**Comment by ryanxcharles** [comment]
Hi Willy, great work. Some thoughts after an initial pass:
* Don't use jQuery
* hashbuf is always a buffer, never hex. Don't mix types.
* You did "git merge" to get changes into your PR. That is fine for now, but should be changed to a "git pull --rebase" before merging into master. A bunch of my commits appear in your PR. Rebase will make the commit history more linear.

Will add more comments later.

**Comment by willy-b** [comment]
Datt Setup - Create identity screen (from Chris' mockup) now works:
Datt create identity modal (from Chris' mockup)

Datt Setup - Restore identity screen (from Chris' mockup) present but not functional yet:
Datt restore identity modal (from Chris' mockup)

**Comment by willy-b** [comment]
@ryanxcharles Thanks for the review. I can definitely rebase before we merge. 
Regarding jQuery: I'm ONLY using jQuery for showing/hiding the Bootstrap Modal (setup modal), because Bootstrap JS uses jQuery. Looking into removing that dependency.

**Comment by ryanxcharles** [comment]
Second pass (written before I noticed your above comments):
* For the bootstrap stuff that uses jQuery, just don't use bootstrap's javascript. All things can be accomplished without using it. If UI features are most easily accomplished with jQuery, just don't do those UI features now.
* I believe there are plugins for React to do routing. That is probably a better way than jQuery.
* CSS style should have two space indentation.
* HTML style should have two space indentation.
* Please limit commit message headers to 50 chars. Put remaining text in a message blow the header. See all of my commits for how to do this.

**Comment by willy-b** [comment]
Content/posts now support Markdown formatting. Added a body to user announcement messages which showcases this:
New user announce message showing Markdown in Content

**Comment by willy-b** [comment]
Hey @ryanxcharles ,
Thanks again for the code review. 
- Re jQuery: Good news, I am not using jQuery for routing. Only to support Bootstrap's modal transitions. We should replace that too but given it is <5 lines of total influence, I would argue that it is a post-MVP concern. 
- I'll fix the 2-space indentation for HTML / CSS now
- When I rebase I will address the commit messages. Thanks for holding us to a high standard w.r.t. to our commit-style/documentation ; it will make it much more pleasant for developers coming on board later (and for ourselves in future)
- We can add React Router plugin, but I would argue the added complexity makes it a post-MVP move. I prototyped with and without and the code without is much simpler at this stage.

**Comment by willy-b** [comment]
N.B. almost all of this UI has been pulled back out of master and is now waiting in PR #93

**Pull request merged**
